# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SP9d-EEslRZPSlEJnZQv3VDSKc65fN8g
"""

import numpy as np
matriz=np.array(
    [
     [2,-5,-11,0],
     [-9,4,6,3],
     [4,7,12,-2]
     ]
    )

print(matriz)
print(matriz[1][1])
print(matriz[1][3])
print(matriz[0][2])

lista=[
     [2,-5,-11,0],
     [-9,4,6,3],
     [4,7,12,-2]
     ]
matriz=np.array(lista)
print(matriz)

print(lista[1][3])
print(lista[0][2])
print(matriz[0,3])

for fila in matriz:
  for celda in fila:
    print(celda)

for i in range(len(matriz)):
  for j in range(len(matriz[i])):
    print(f"({i},{j}):{matriz[i,j]}")